sudo: required
services:
    - docker

before_install:
    - docker build -t bellom/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bellom/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Docker-env"
    bucket_name: "the-name-of-the-backet-from-s3"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"